#!/nix/store/l2xyarvzahpz3fysr9hqbvcsgv5gnrnk-coreutils-9.1/bin/env tcsh

# strip all the dependencies out of the makefiles so it compiles quicker

if ( ! -d  tools ) then
 echo 'must be run in top level dir'
endif

tools/safe >& /dev/null
foreach f ( */Makefile )
  mv $f $f.saved
  cat $f.saved | sed '/ DEPENDENCIES/,$d'  > $f
end

