#!#!/nix/store/l2xyarvzahpz3fysr9hqbvcsgv5gnrnk-coreutils-9.1/bin/env tcsh

# reverse the effect of danger

if ( ! -d  tools ) then
 echo 'must be run in top level dir'
endif

foreach f ( */Makefile.saved )
  mv $f $f:r
end

